name: Builds

on:
  push:
    branches:
      - main
  pull_request:

env:
  UNATTENDED: 1
  SDK_VERSION: 14.0
  TARGET_DIR: /tmp/osxcross_target

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-deploy
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a script
        run: |
          ./build.sh
        shell: bash

      - name: Rename Files
        run: |
          find ${{ env.TARGET_DIR }} -name "*::*" -type f | while read -r file; do mv "$file" "${file//:/_}"; done
        shell: bash

      - name: Compress Directory
        run: |
          zip -r osxcross_target.zip ${{ env.TARGET_DIR }}
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: osxcross_target
          path: ./osxcross_target.zip
